### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by rithvikvibhu** [fingersonfire/Whatsapp-Xtract#3]
The new version (#2) has a pretty good readme (named `!README.txt`) and I think it should replace the current visible one (`README.md`).

Also, it would be nice to credit the author [ztedd](https://forum.xda-developers.com/member.php?u=3594618) along with the (existing) link to the XDA thread.

**Comment by Juarez83** [comment]
[
Duplicate of #

**Comment by rithvikvibhu** [comment]
There are 3 issues in this repo in total (closed and open). None of the other issues are related to README. What exactly is this a duplicate of?

**Comment by fingersonfire** [comment]
Nice suggestion. I have now merged the Readme files as suggested.
